SRC_CPPS = \
           connect.cpp \
		   stream.cpp \
		   ImageAcquisition.cpp \
		   ConfigurationReader.cpp \
		   CameraControl.cpp \
		   BackupConnection.cpp \

EXEC     = CameraControl

include ../sample.Makefile
